FROM alpine:3.11
RUN apk update \
 && apk add nginx openssl \
 && apk add openrc

RUN	openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/example.key -out /etc/nginx/example.crt -subj "/C=FR/ST=IDE/L=Paris/O=42/OU=42/CN=mywebsite.com" 

RUN mkdir -p /run/nginx \
    && ln -sf /dev/stderr /var/log/nginx/error.log \
    && ln -sf /dev/stdout /var/log/nginx/access.log

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./index_nginx.html /var/www/

EXPOSE 80 443

#CMD ["nginx", "-g", "daemon off;"]
COPY ./nginx.sh /nginx.sh
RUN chmod 777 /nginx.sh

ENTRYPOINT ["sh", "/nginx.sh"]