FROM alpine:3.11

RUN apk update
RUN apk add wget nginx openrc supervisor php7 php7-fpm php7-opcache php7-gd php7-mysqli php7-zlib php7-curl php7-mbstring php7-json php7-session
RUN mkdir /www

COPY ./setup.sh /setup.sh
